#!/bin/python3

import math
import os
import random
import re
import sys


#
# Complete the 'diagonalDifference' function below.
#
# The function is expected to return an INTEGER.
# The function accepts 2D_INTEGER_ARRAY arr as parameter.
#

def diagonalDifference(arr):
    # Write your code here
    sum1 = 0
    sum2 = 0
    flag1 = len(arr) - 1
    flag = 0
    for m in arr:
        sum1 += m[flag]
        flag += 1

        sum2 += m[flag1]
        flag1 -= 1

    result = abs(sum2-sum1)

    return result


# if __name__ == '__main__':
#     fptr = open(os.environ['OUTPUT_PATH'], 'w')
#
#     n = int(input().strip())
#
#     arr = []
#
#     for _ in range(n):
#         arr.append(list(map(int, input().rstrip().split())))
#
#     result = diagonalDifference(arr)
#
#     fptr.write(str(result) + '\n')
#
#     fptr.close()


n = int(input().strip())

arr = []

for _ in range(n):
    arr.append(list(map(int, input().rstrip().split())))

result = diagonalDifference(arr)

print(result)
